In [7]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
print(list_)
print(array_list)

['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Arrays can only store elements of the same data type, but lists can store elements of different data types. But data type of both will be different.

In [8]:
import numpy as np
list1 = [ '1' , '2' , '3' , '4' , '5' , 'Aamir']
arrlist =np.array(list1) 
print(list1)
print(arrlist)


['1', '2', '3', '4', '5', 'Aamir']
['1' '2' '3' '4' '5' 'Aamir']


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [5]:
for i in list1:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
for i in arrlist:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [11]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list,dtype=int)

In [12]:
print(num_list)
print(num_array)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [14]:
print(type(num_list))

<class 'list'>


In [15]:
print(type(num_array))

<class 'numpy.ndarray'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [19]:
import numpy as np
print(np.size(num_array))
print(np.shape(num_array))

6
(2, 3)


In [20]:
import numpy as np
print(np.size(num_list))
print(np.shape(num_list))

6
(2, 3)


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [23]:
import numpy as np
zarr=np.zeros((3,3))
zarr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [25]:
import numpy as np
iarr=np.eye((5))

In [26]:
iarr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])